FROM ubuntu:24.04

ARG QT_VERSION=6.8.3
ARG QT_MODULES="qtcharts qtlocation qtpositioning qtspeech qt5compat qtmultimedia qtserialport qtimageformats qtshadertools qtconnectivity qtquick3d qtsensors"

# 新增：支持构建时指定用户 ID
ARG USER_ID=1000
ARG GROUP_ID=1000

ENV DEBIAN_FRONTEND=noninteractive
ENV DISPLAY=:99
ENV QT_PATH=/opt/Qt
ENV QT_DESKTOP=$QT_PATH/${QT_VERSION}/gcc_64
ENV PATH=/usr/lib/ccache:$QT_DESKTOP/bin:$PATH

COPY tools/setup/install-dependencies-debian.sh /tmp/qt/
RUN /tmp/qt/install-dependencies-debian.sh

COPY tools/setup/install-qt-debian-docker.sh /tmp/qt/
RUN /tmp/qt/install-qt-debian-docker.sh

RUN locale-gen en_US.UTF-8 && dpkg-reconfigure locales

RUN git config --global --add safe.directory /project/source

RUN usermod -u ${USER_ID} ubuntu && \
    groupmod -g ${GROUP_ID} ubuntu && \
    mkdir -p /project && chown -R ubuntu:ubuntu /project

WORKDIR /project/build
USER ubuntu

CMD cmake -S /project/source -B . -G Ninja -DCMAKE_BUILD_TYPE=Release && \
    cmake --build . --target all --config Release && \
    cmake --install . --config Release